[package]
name = "igris-accel"
version = "0.1.0"
edition = "2021"
description = "Accelerated operations for the igris service"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
# Enables fast-math operations.
fast-math = []

[dev-dependencies]
rand = "0.8.5"
simsimd = "4.2.2"

criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "bench_dot_product"
harness = false

[[bench]]
name = "bench_cosine"
harness = false